<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="LogRules/*.json" LogicalName="bundled_rules/%(Filename)" />
    <EmbeddedResource Include="LogRules/ATLYSS/*.json" LogicalName="bundled_rules/ATLYSS/%(Filename)" />
  </ItemGroup>
</Project>
